name = "Forever World Modpack"
author = "Sam302rk"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c826c4472ca248e127103f7679bbaae0c1007c1a8f5a9252f877c31aa7be41d5"

[versions]
minecraft = "1.21.4"
quilt = "0.28.0-beta.6"

[options]
acceptable-game-versions = ["1.21"]
